name: splatam
channels:
  - nvidia/label/cuda-12.1.0
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit
  - cudatoolkit=12.1.0
  - python=3.10
  - pytorch=2.1.0
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - tqdm=4.65.0
  - Pillow
  - faiss-gpu
  - opencv
  - imageio
  - matplotlib
  - kornia
  - natsort
  - pyyaml
  - wandb
  - gxx_linux-64=10
  - pip
  - pip:
    - lpips
    - open3d==0.16.0
    - torchmetrics
    - cyclonedds
    - submodules/diff-gaussian-rasterization-w-depth
    - submodules/simple-knn